### ISSUE TITLE
Explosion when playing with the basic styles

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-engine#922] opened 2017-04-18 16:28 UTC
![apr-18-2017 18-25-46](https://cloud.githubusercontent.com/assets/1057056/25141734/c252bcb2-2464-11e7-8d7e-79e4459434a8.gif)

**Comment by oskarwrobel** [comment] 2017-04-18 16:33
The same is on https://ckeditor5.github.io/

**Comment by ma2ciek** [comment] 2017-04-18 17:20
I can also reproduce it - hitting twice italic button on the text containing an edge of the bold fragment.

**Comment by Reinmar** [comment] 2017-05-04 11:02
Similar one (in terms of steps) https://github.com/ckeditor/ckeditor5-engine/issues/711.

**Comment by oleq** [comment] 2017-06-21 13:25
I spent a couple of minutes debugging this issue and here's a little I have found. For the following data in the editor (after bold and italic)
```html
<p>This <i>[is <strong>an]</strong></i><strong> editor</strong> instance.</p>
```

the second italic command execution (like in the screencast) fails in `DomConverter`. In `viewPositionToDom()` there's an attempt to `getCorrespondingDomText()` for a `Text` "an editor", which is a child of `AttributeElement` (strong). 

The algorithm falls into [this](https://github.com/ckeditor/ckeditor5-engine/blob/master/src/view/domconverter.js#L760) condition and `this.getCorrespondingDom( viewText.parent )` returns `null` because `getCorrespondingDomElement()` for such `AttributeElement` is not found in `_viewToDomMapping`.

I'm not quite sure why it is so but something tells me either:
1. the `AttributeElement` has not been properly registered in the mapping,
2. something removed it from it in the meantime so the algorithm works on desynced DOM/view,
3. the algorithm should have never fallen in this flow for some other reason.

I suppose some more serious view vs. DOM debugging is necessary to figure it out. I hoped a simple fix will do the trick but I'm afraid there's none 😞.

**Comment by Reinmar** [comment] 2017-06-21 20:20
I think that https://github.com/ckeditor/ckeditor5/issues/453 is a DUP of this ticket, but we need to confirm it after fixing this one.

**Comment by Reinmar** [comment] 2017-06-21 20:43
One more TC to test after fixing this issue: https://github.com/ckeditor/ckeditor5-basic-styles/issues/46. Since I closed it as a DUP of this, if it turns out that it's a different issue, it needs to be reported here.

**Comment by Reinmar** [comment] 2017-06-22 10:48
Two more similar tickets: https://github.com/ckeditor/ckeditor5-list/issues/58 and  https://github.com/ckeditor/ckeditor5-engine/issues/701.

**Comment by szymonkups** [comment] 2017-06-23 14:59
We had a debugging session with @Reinmar and we came up to some conclusions. We mainly focused on test case reported by @oskarwrobel. Thing is that there are situations when `Renderer` is not rendering text nodes when its parent node is marked to render ([here](https://github.com/ckeditor/ckeditor5-engine/blob/f1fa1b1934315d1086afcc052a5ee7dd5f54ae72/src/view/renderer.js#L202)). This happens in our case so the text node is not updated correctly and incorrect DOM is rendered. This way we are out of sync and probably further selection rendering is also incorrect (uncaught exception).

**Comment by Reinmar** [comment] 2017-06-23 15:05
During a short discussion with @pjasiun we agreed that it should be `_updateChildren()` who updates its text nodes.

Why we can't rely on `render()` calling `_updateText()`? Because at that point (before `_updateChildren()` is executed) text nodes may not be in the same order and places where they are in the view. View to DOM mapping uses the nodes order to find the matching DOM text nodes, so if we tried to update texts at that point we might update completely different text nodes.

Therefore, we prevent updating text nodes which parent elements are about to be updated too. But this means that we may get outdated text nodes in the DOM after `_updateChildren()`.

And therefore, `_updateChildren()` needs to update text nodes after updating the order of nodes.

**Comment by Reinmar** [comment] 2017-06-27 08:37
> And therefore, _updateChildren() needs to update text nodes after updating the order of nodes.

It turned out to not be true.

The `_updateChildren()` uses `viewToDom()` which always returns a new text node. So:

* **if** children of elements were modified, this ensures that mapped DOM children are fine.
* **if not**, then `_updateText()` is called.

The issue, as found by @szymonkups, is somewhere else. Or at least part of the issue.

Let's consider this example. We're changing:

```html
<p><i><b1>foo</b1></i><b2>bar</b2></p>
```

to:

```html
<p><b1>foobar</b1></p>
```

`markedChildren` contains `<p>` and `<b1>`.

First, we call `_updateChildren( p )`:

1. Remove `<i><b1>foo</b1></i>`.
2. Remove `<b2>bar</b2>`.
3. Insert `<b1>foo</b1>`.

Unfortunately, on step 1, we unbind `<b1>` (which we already have cached in https://github.com/ckeditor/ckeditor5-engine/blob/e6e92e983b75a036761eb8fc253ebf805d14f771/src/view/renderer.js#L452). But then (in step 3) we insert the unbinded  `<b1>` again which creates a completely invalid DOM which isn't bound to the view and which isn't updated in `_updateChildren( b1 )` which is called right after this.

The solution: don't unbind elements which are in the view or will be in the DOM after the changes.

**Comment by Reinmar** [comment] 2017-06-27 08:40
While analysing this we also noticed that it's unclear where the renderer uses `getCorrespondingDomText()`. This method has a very narrow use case because it assumes a lot about the position of the text node that it looks for in the DOM.

So, our idea is to remove `getCorrespondingDom()` method and use the underlying `getCorrespondingDomElement()` and `getCorrespondingDomText()` directly. It will turn out that the latter is used in just one place which is `_updateText()`. In this case it's safe because `_updateText()` is only called if parent element wasn't modified at the same time.

We should also warn about this in `getCorrespondingDomText()`.

**Comment by Reinmar** [comment] 2017-06-27 08:42
It's also worth linking to https://github.com/ckeditor/ckeditor5-engine/issues/888 as it's the change which introduced unbinding. It may contain interesting information.

**Closed** 2017-06-30 14:20 UTC
Labels: candidate:1.0.0, status:confirmed, type:bug
