### ISSUE TITLE
[Safari] Selection is locked in a nested editable

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1157] opened 2017-10-03 09:58 UTC
You can't leave a nested editable by clicking somewhere in editor's content outside of that nested editable because engine re-renders selection inside that nested editable:

![oct-03-2017 11-56-51](https://user-images.githubusercontent.com/156149/31119675-05482696-a832-11e7-926c-c956eb6ac6f6.gif)

I can reproduce it e.g. here: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/classic-editor.html

**Comment by scofalik** [comment] 2017-10-03 10:19
Looks serious, how it is possible and how did we missed it? Why would the selection be rendered there?

**Comment by pjasiun** [comment] 2017-10-03 10:30
So many questions, so few answers.

**Comment by Reinmar** [comment] 2017-10-03 11:04
:trollface:

**Comment by scofalik** [comment] 2017-10-03 14:14
Could be related to #1153

**Comment by scofalik** [comment] 2017-10-03 14:34
TBH, I cannot reproduce it. I am using Safari version `Version 11.0 (12604.1.38.1.7)`

**Comment by Reinmar** [comment] 2017-10-03 14:36
Do you try it in the docs?

I can reproduce it even on https://ckeditor5.github.io

Safari Version 11.0 (12604.1.38.1.7)

**Comment by scofalik** [comment] 2017-10-03 14:39
Yes, I tried in docs:

![oct-03-2017 16-40-10](https://user-images.githubusercontent.com/1502228/31131057-5e6942d8-a859-11e7-9b04-b84655da73ec.gif)

**Comment by Reinmar** [comment] 2017-10-03 14:47
Strange. I can constantly reproduce it. I even changed the way I click (mouse vs trackpad). Dunno. So, let's wait for other to reproduce it.

**Comment by Mgsy** [comment] 2017-10-03 14:54
> how did we missed it?

We didn't :D https://github.com/ckeditor/ckeditor5/issues/557.

I will close the issue in the main repository.

**Comment by scofalik** [comment] 2017-10-04 06:00
If you can reproduce it, can you go to file `ckeditor5-engine/src/view/observer/focusobserver.js`, and change:
```javascript
this._renderTimeoutId = setTimeout( () => document.render(), 0 );
```
to
```javascript
this._renderTimeoutId = setTimeout( () => document.render(), 100 );
```
And see if that helped?

**Comment by scofalik** [comment] 2017-10-04 06:29
Okay for some reason I started to be able to reproduce it :O. I can confirm that the fix above does help.

**Comment by Mgsy** [comment] 2017-10-04 07:57
> I can confirm that the fix above does help.

I also checked it and it works great 👍

**Closed** 2017-12-12 09:47 UTC
Labels: candidate:1.0.0, status:confirmed, type:bug
