### ISSUE TITLE
Simplify model to view conversion

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#829] opened 2017-02-21 14:50 UTC
When analysing https://github.com/ckeditor/ckeditor5-list/issues/13#issuecomment-281062365 we realised that ensuring model's correctness by post-fixing operations which lead to an incorrect model isn't feasible due to how conversion works. We convert every atomic operation so the incorrect state needs to be handled by converters. This means that converters may need to accept some really odd scenarios. The more complex feature, the more complex the converters would need to be. This is definitely the wrong way.

At the same time, we are generally worried that the change conversion is a tricky concept. It allows us to compose independent features which is a crucial aspect of a pluggable architecture of CKEditor, but it's not an easy concept to understand nor to debug. The alternative to an event-based change conversion is e.g. a functional approach with immutable data structures in which the entire model (or, if optimised, its changed fragments) gets processed, but the composability of features and other requirements remain tough topics which need to be considered in every approach. Without a full, real-life implementation we wouldn't know if any other approach, especially a conceptually different one, would work better than the current one.

Nevertheless, we need to think on improving conversion in a way that it will be digestible for developers (us included, in fact). Since we can't replace the entire concept, we should at least try to make it as simple as possible.

Let's get back to the grannularity of conversion. We convert operations, so not even deltas (which contain multiple operations). This is a super fine level which has one advantage – there are just a few types of changes to convert:

* insert,
* remove,
* move,
* rename,
* change attribute (on text and elements).

However, the fine granularity means that if a semantical change (like quoting a nested list item) needs to perform more operations in order to lead to a correct state (in this case of lists+quote it's move + change attribute), we're dealing with incorrect states during conversion, regardless of the order in which we'll apply both operations (we were considering pre-fixing and post-fixing).

This leads us to a conclusion that **conversion should be triggered only on `#changesDone` event**, which is a feature controlled moment in time when all changes are finished.

Question is – how to do that?

# Proposal

## Remove superfluous conversion events

The move and rename operations are needed by OT, but during the conversion they can be easily replaced by sets of remove and insert. After all, we're converting the model to a virtual DOM (called "the view"), so we can do excessive operations there without a significant negative impact on performance.

The new list of changes contains only 3 operations to convert:

* insert,
* remove,
* change attribute.

Read this as – if a change happened, we remove the changed things and reinsert their newly converted version again. Yes, this is pretty similar to an immutable data structure approach (but no, in deep the view isn't immutable, so we maintain the same way to compose features).

## Buffer changes in the `ModelConversionDispatcher`

As mentioned already, the changes must be converted on `#changesDone` event which means that they need to be buffered for a time being. In one conversion batch (not to confuse with model batches ;|) we can have multiple dependent operations applied to the model. What we need to understand is how to dispatch them in a way that there will be no conflicting operations converted.

Example:

```html
<listItem indent=1>a</listItem>
<listItem indent=2>b</listItem>
```

The user wants to quote the "b" item. So we have three model operations:

1. insert `<quote>` at the end (could be at position `[1]` too in fact),
1. move `<listItem indent=2>` to that `<quote>`,
1. change `indent=2` to `indent=1` (post-fixer).

### Simple, incorrect implementation

Let's consider a simple `ModelConversionDispatcher` implementation where these changes are converted in nearly-like-model way:

1. insert `<quote>` at the end (this is fine) or at position `[1]` (already incorrect state where we have item with `indent=2` right after `<quote>`)
1. remove `<listItem indent=2>` (ok),
1. insert `<listItem indent=2>` in `<quote>` (incorrect in for both insertion positions in step 1, due to incorrect attribute value, but let's say correct because in model it's already fixed – still, hard to analyse inside a converter),
1. change `indent=2` to `indent=1` (makes everything correct again... but in fact that change doesn't need to be converted if already considered in step 3).

As we can see, it didn't help much – insertion of the `<quote>` already leads to an incorrect model (there can be more list items after "b" which means that there's no way out). Later, it may not be any better.

### Simple stupid implementation

A different approach would be if `ModelConversionDispatcher` removed entire view content and reconvert the entire model (which at this stage is always correct) on every `#changeDone`. Just like `setData()` does.

This seems to be extremely easy to implement, but has the obvious negative performance impact. This isn't a feasible implementation taken that the editor must be able to handle longer documents and that when typing a single letter you'd need to reconvert the entire model.

However, it's something which allows us to test the entire approach. We can quickly prototype the change buffering concept and test it on real editor with real features because it's like using the `setData()` function. We'll be able to see how removing move and rename conversion events affects the editor.

### Final implementation

This is something open to research. Without an in deep analysis it will be impossible to understand what's the best way to buffer changes. Also, we could imagine multiple levels of optimisations. On one extremum there is the KISS implementation described in the previous section and on the other extremum a perfectly optimised one.

But, to start, for the scenario mentioned above, I could imagine such steps:

* remove `<listItem indent=2>`,
* insert `<quote>`,
* insert `<listItem indent=1>` to the `<quote>`.

Cheers!

**Comment by pjasiun** [comment] 2017-02-21 16:41
> Simple stupid implementation

I don't like this solution proposal. 

First, note that it's not only the whole conversion but creating the whole view (using `writer.wrap` for each attribute on each node). Then renderer will have no idea which element changed and need to compare all of them with the DOM. Renderer use instanced to tell that elements are the same, so if the whole view is new, **the whole DOM need to be rebuild**. And it happens every time user type a letter. Writer and renderer are not optimized to do it. 

Second, you started from the fact that converters are too complicated. Even though I agree, I don't think that these changes fix it. Conversion is that complicated because of calling a lot of small function, dynamically generate, so you have no good place you could put the debugger. With the proposal of rebuild whole document there will be even more converting functions called (if I put debugger in the converters generating factory now I have ~10 calls and after the change there will be more then 100, so if my `debugger` will be called that many times with every single change I will have not way to find which one causes the issue.

Finally, it will prove nothing. We can replace `move` and `rename` with `insert` and `remove`  without the rerendering the whole document. What it could prove is if the converting on `changesDone` is possible. But as a was developing converter, most problems I had with delayed conversion were connected which finding the right place in the modified model and map it into a good place in view. This is why I finally gave up, and converters are called as soon as possible. In you proposal, this problem does not exist at all so we will not prove if we can solve it. It does not use mapper which is the most tricky part. So the only thing it will prove is that it is doable in the brute-force way.

> At the same time, we are generally worried that the change conversion is a tricky concept...

Since I agree that the solution will be needed at some point, I don't think any of proposed solutions will make converters simpler. Instead, they will be even more complicated, mostly because of the introducing another layer of events and mapping positions on the modified model (what will be the source of numerous bugs).

However, for sure replacing `move` and `rename` with insert and remove will simplifies conversion. Also, your last proposal will make writing complex converters simpler (even if debugging will be more complicated).

**Comment by pjasiun** [comment] 2017-02-21 16:55
Note, that I commented only parts I disagree.

I totally agree that we should replace `move` and `rename` with insert and remove. 

And I agree that converting intermediate state is wrong because it can not be correct.

**Comment by Reinmar** [comment] 2017-02-21 17:06
> I don't like this solution proposal.

Aaaa! THIS WAS ONLY A PROPOSAL FOR A PROTOTYPE. It has super obvious flaws, so I'll skip a big part of your comment about them. That absolutely irrelevant now that you'll debugger will be triggered 100 times (which isn't even true because if placed in such a way it'd be triggered that many times when loading the data too).

> Renderer use instanced to tell that elements are the same, so if the whole view is new, the whole DOM need to be rebuild

This is something I was not aware of and is, unfortunately, very important ;/ This is indeed a blocker for the prototype... Pity that it works this way, but I remember now that the alternative with comparing nodes without references would be very inconvenient too.

> Since I agree that the solution will be needed at some point, I don't think any of proposed solutions will make converters simpler. Instead, they will be even more complicated, mostly because of the introducing another layer of events and mapping positions on the modified model (what will be the source of numerous bugs).

You kinda assume here that now things go smooth because we convert granular things, so this change will make things more complex. While the truth is that we already have I guess dozens of issues with the mapper, positions in conversion events (I'm right now dealing with one in `ModelConversionDispatcher`) and the issues mentioned initially in this ticket and perhaps more. Taken that, despite introducing the buffering layer, the new proposal may not be that bad. Especially that we couldn't come with any other proposal so far.

**Comment by Reinmar** [comment] 2017-02-21 17:12
That said, I think that we agree that if we want to trigger conversion on `#changesDone` we need some buffering. Also, in order to never convert incorrect changes, that buffering layer can't simply dispatch all the original events – it needs to somehow process them.

So, isn't the proposal mentioned in "Final implementation" the only possible solution? I don't see a room for alternatives here...

**Comment by scofalik** [comment] 2017-02-21 20:17
As we have different experiences with this part of code, it's good to agree on some baselines and continue from there. I also agree that conversion could happen on `changesDone` and that removing `move` converter may be positive. It's worth noting that AFAIR all features except of `List` use default `move` converter anyway, while `List` move converter does very similar thing to `List` remove and insert converters, so it slots into this new concept.

It should also simplify writing converters, and through this - debugging them.

I've been thinking about this a lot today. I think there is little gain in prototyping the solution as @Reinmar proposed (the "setData" solution). As @pjasiun stated it will prove nothing, or even will be "false negative" -- I don't expect such solution working flawlessly so we may draw incorrect conclusions.

Instead of that we should focus on close-to-target-solution.

As we all agree, we have to buffer (or mark) changes done on model. We have something similar already in view (changed view nodes are marked to sync with DOM) but there are important differences, unfortunately.

First of all, in view, we mark nodes so they can be then diffed with DOM. The marking mechanism is very simple because the logic happens during diffing. Unfortunately this is impossible with model as we don't have anything to diff with. So we have to have a better marking solution.

Another problem are `Text` nodes. In model they are volatile and we cannot store references to them. This means that marking `Text` nodes is difficult. We could mark inserted `Text` nodes but the real problem are removed ones, as we would not know from where we removed them. (BTW. Whenever `TextProxy` is changed we can just mark the whole `Text`).

Of course, again, we can just mark the parent that it's children changed but then we potentially re-convert big chunks of model tree (remember - no diffing here, so if parent is marked, we have to re-convert it all).

So, there are two basic concepts how we do it:

1. Buffer all changes in a form similar to what is now passed in `change` event. Keep the `range` that changed together with change type and additional data. The trick here is that we would have to update buffered ranges (like `LiveRange`). We cannot use `LiveRange` though. If we have a `LiveRange` for attribute change and then something is inserted into it, the original range should be split, but `LiveRange` won't. We can use however new methods introduced in `Range` (`_getTransformedByDocumentChange` AFAIR :P). I like this solution because it will be exact but it's more complicated and less efficient (many transformations). BTW. in this solution, removed parts of tree are kept as `LivePosition`s with information about how many nodes were removed.

2. Buffer changes on elements by marking the elements, mark also all changed `Text` nodes (that haven't been removed) but keep `LivePosition`s for removed `Text` nodes. This is less complicated but I don't like the "dual" nature of this solution - you mark some changes as elements while some changes as positions.

**Comment by Reinmar** [comment] 2017-02-22 09:10
> Of course, again, we can just mark the parent that it's children changed but then we potentially re-convert big chunks of model tree (remember - no diffing here, so if parent is marked, we have to re-convert it all).

I really wouldn't worry about this. A single block (like paragraph, list item, etc.) will never become a huge piece of content. A table may, but not the lowest level blocks.

So, if only we're able to mark only children of the paragraph to re-convert and not the paragraph itself so we wouldn't break the reference with the DOM. I refer here to what @pjasiun mentioned, that the renderer diffs the DOM with the view by references, but I assume that this happens only down to the view container element level – attributes are not compared by references (am I right?).

Also, we can think on optimising this so an insertion of a single letter wouldn't trigger the conversion of the entire paragraph content. Typing is the only operation which happens so often that it might be an issue for conversion (especially when taking collaborative typing into consideration).


> Buffer all changes in a form similar to what is now passed in change event.

I think that I really don't like this option :D. Isn't it like what I described in "Simple, incorrect implementation"? One of the main goals of this entire effort is to avoid converting changes which temporarily create incorrect state. The model may be fixed already (if we buffer changes), but the order of their conversion still matters IMO (as I tried to show in my original post).

> EDIT: BTW. This approach should not add more issues to the position mapping than we have. Actually, it may make it more stable.

That's really good to hear :D

**Comment by scofalik** [comment] 2017-02-22 09:34
> I think that I really don't like this option :D. Isn't it like what I described in "Simple, incorrect implementation"?

I guess you are partially right. I meant to store (live/transformed) ranges with data so it's similar to what we have now. The difference would be that they are converted on `changesDone` which mean that fixers could fix model already.

But I am also for the second solution.

**Comment by pjasiun** [comment] 2017-02-22 10:10
> So, if only we're able to mark only children of the paragraph to re-convert and not the paragraph itself so we wouldn't break the reference with the DOM. I refer here to what @pjasiun mentioned, that the renderer diffs the DOM with the view by references, but I assume that this happens only down to the view container element level – attributes are not compared by references (am I right?).

No. All view elements are bind with corresponding DOM elements by references. Only text nodes are not, but they are bind by sibling elements. So if we re-render paragraph (all attribute elements) the whole content will be re-rendered.

**Comment by pjasiun** [comment] 2017-02-22 10:15
It's not and never was a renderer role to prevent rendering if the part of the view was rebuild. The architecture was never designed to do it, including `view.writer` which is optimized to do the smallest change possible.

**Comment by pjasiun** [comment] 2017-02-22 11:41
> conversion should be triggered only on #changesDone event

In general, more I think about it more I feel that this is a move in a wrong direction. The current solution is not perfect, but I don't think there is a perfect solution. We spend a lot of time polishing what we have and if we will change the way converters work we will, to some point, start from scratch. I don't believe that we will find a solution which will not need hacking in some cases.

The problem with the current solution is that converters need to be able to handle intermediate, wrong state of the document. It is inconvenient, but it is not impossible.

In this case, we have some solution.

1. We can check what is the indent level of the previous model list item. If there is no previous model list item or the indent level is the same then the converting list item should no be indented. If it is bigger, then we should intent list by the difference (or always 1 level).

2. No one said that converters need to do changes immediately. Even if converters are called as soon as change appear, some of them can do nothing, if we know that there will more changes and want to handle them together.

3. I this case we can decide that the expected behavior is to quote the whole list (https://github.com/ckeditor/ckeditor5-message-quote/issues/2). I know that it is avoiding issue instead of fixing it, but I believe that sometimes avoiding the issue is the way to go.

I'm not saying that we will not meet the point where we need to change the way how converters work, but I don't think it's now.

**Comment by Reinmar** [comment] 2017-02-22 12:11
> No. All view elements are bind with corresponding DOM elements by references. Only text nodes are not, but they are bind by sibling elements. So if we re-render paragraph (all attribute elements) the whole content will be re-rendered.

What you wrote, @pjasiun, means that if we'd want to implement the proposed solution, we'd need even more changes than I expected, so there's no point in investigating this option further now. We may get back to it later and keep our heads open for new ideas in the meantime.

**Comment by scofalik** [comment] 2017-02-22 12:15
Wait, I don't understand what @pjasiun post bring in that changed your mind. Few posts above you write that you are fine with re-rendering whole paragraph in DOM.

**Comment by Reinmar** [comment] 2017-02-22 12:24
Re-converting, not re-rendering. I might've not been clear, but what I meant was that it's fine to do whatever we want with the view as long as the DOM doesn't need to be re-rendered. This is especially important when typing – we should try as much as possible to not do any changes to the text if typed characters convert back to a view matching the current DOM.

Let's consider this:

```html
<p>x^y</p>
```

1. Someone types "z" so the DOM changes to `<p>xz^y</p>`
1. We insert it in the model: `<paragraph>xz^y</paragraph>`
1. Convert this somehow to the view: `<p>xz^y</p>`
1. Now, the renderer must be able to understand that the view matches the DOM so there's nothing to touch.

The step 3 is critical here. I thought initially that renderer compares view with the DOM by checking element names, attributes and text data. This would mean that we could rebuild entire view and everything would be fine.

Then @pjasiun wrote that all view elements are bound to all DOM elements. This means that we can't even freely re-convert entire `<paragraph>` content because it might re-convert `<strong>` elements in the view which would mean that the renderer would need to rebuild entire `<p>` content in the DOM.

If renderer would work differently we'd have more freedom with the conversion. But we don't, so that's why I wrote now that any re-conversion is a bigger issue than I thought.

BUT, please do note that I'm only worried about re-rendering in case of text operations (typing). If some bigger changes are done to the DOM (e.g. backspace is pressed to merge two blocks), then IMO we can re-render that bigger part of the DOM.

**Comment by scofalik** [comment] 2017-02-22 12:28
So I assume that we are fine with this in context of getting rid of `move` and `remove` events in `ModelConversionDispatcher`?

**Comment by Reinmar** [comment] 2017-02-22 12:36
Yes, I think it makes sense to checking now if we can remove them easily. Also, they don't affect rendering because `move` and `rename` don't happen while typing.

**Comment by Reinmar** [comment] 2017-02-22 12:37
Actually, we've said already that conversion should use those operations which are possible in the DOM :) Move and rename are not. Move in the DOM behaves like "remove + insert" anyway (iframe gets unloaded) and rename is pure "remove + insert".

**Comment by Reinmar** [comment] 2017-02-22 13:11
> In general, more I think about it more I feel that this is a move in a wrong direction. The current solution is not perfect, but I don't think there is a perfect solution. We spend a lot of time polishing what we have and if we will change the way converters work we will, to some point, start from scratch. I don't believe that we will find a solution which will not need hacking in some cases.
> 
> The problem with the current solution is that converters need to be able to handle intermediate, wrong state of the document. It is inconvenient, but it is not impossible.

I'll repeat here what I wrote you in priv – building anything on an unstable ground will not lead to something good, no matter how much you'll polish it.

I understand that we got far with the solution that we have, but here we have a question whether it's reasonable to go further. It's the second post-fixer that we want to implement and we already have problems. Imagine more complex data models with more rules. 

Another point is that we can't push too much responsibility on converters. This code will be spread all around the features meaning it awful fragmentation and little control. This is especially dangerous with 3rd party code. Therefore, if I had to choose I'd rather have super complex MCD and renderer if they provide stable grounds for easier conversion because these mechanisms are closed and controlled by us.

**Comment by scofalik** [comment] 2017-02-23 12:31
I've made a first step to simplify the conversion: issue #837, PR #838

**Comment by Reinmar** [comment] 2017-10-11 10:58
Copied from https://github.com/ckeditor/ckeditor5-engine/issues/778:

If things like https://github.com/ckeditor/ckeditor5-image/issues/31 are required, then we have a problem, either with the concept itself or how we sell it.

As we know, the concept of converting a change has its merits and it's unlikely that we'll be able to change it. It allows for a better composition of features and reduces overhead on the changes coming from the collaboration. If we'd like to have dirty fragments conversion, we'd need to translate applied changes to regions to re-convert, including things like selection and markers. Taking feature composition into consideration, it is very hard to imagine such a solution and, very likely, it wouldn't be a clean and clear concept either.

Anyway, apparently we need to work on how we sell the conversion. E.g. if each model change requires its own converter, then converter builders should not propose consuming more than either an element or an attribute. Which means that perhaps:

* We could have some warning that something wasn't consumed (IIRC, this was requested a couple of times already :D). In this specific case, AFAIU, the image src attr wasn't consumed because the builder didn't do that.
* There should be no generic `converterBuilder.from()` method (in fact, I see that it's been just removed, now, only the specialised ones are public).

And finally, we need to be very clear about this in the documentation, other places in the API (like – if you have a converter function, the name should always state whether it converts an element or attribute), etc.

**Comment by pjasiun** [comment] 2018-01-09 16:33
Closed by https://github.com/ckeditor/ckeditor5-engine/pull/1206.

**Closed by pjasiun** 2018-01-09 16:33 UTC
Labels: candidate:1.0.0, module:conversion, status:discussion, type:enhancement, type:feature
