### ISSUE TITLE
Weird result after moving LiveSelection

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-engine#630] opened 2016-10-13 21:53 UTC
Initial data:

```
f<$text italic="true">[o</$text><$text bold="true" italic="true">oba]</$text>r
```

Action:

```
selection.setRanges( [ Range.createFromPositionAndShift( selection.getLastRange().end, 0 ) ] );
```

Expected:

```
f<$text italic="true">o</$text><$text bold="true" italic="true">oba[]</$text>r
```

Result:

```
f<$text italic="true">o</$text><$text bold="true"><$text italic="true">oba</$text></$text><$text bold="true" italic="true">[]</$text>r
```

**Comment by scofalik** [comment] 2016-10-14 06:25
Looks like `Selection` did not refresh it's attributes.

Is this `LiveSelection` instance or `Selection` instance? Have you taken it from `engine.model.Document` instance or created in a different way?

Only attributes of `LiveSelection` from `Document` update automatically when selection is changed. In other cases, you have to do it by hand.

Please check if that's the case. If so, you may propose that we change this behavior (rather unlikely, but we can discuss) or close the issue.

**Comment by oskarwrobel** [comment] 2016-10-14 07:58
It is `LiveSelection` from `Document`.

**Comment by scofalik** [comment] 2016-10-14 07:59
Okay, then I'll look into it, hopefully soon.

If anyone want to look into it by himself, feel free, just remove me from assigneees.

**Comment by Reinmar** [comment] 2017-06-22 13:39
The issue is not with `LiveSelection` because it has just the right attributes (bold and italic). The issue is that `dev-utils/model#getData()` can't stringify this correctly:

```
<$text bold="true"><$text italic="true">oba</$text></$text><$text bold="true" italic="true">[]</$text>r
```

Note that the selection has both attributes here. It's just a different representation.

**Comment by Reinmar** [comment] 2017-06-22 13:43
I added a slightly different test in f1fa1b1. I'll report the issue for dev utils.

**Closed by Reinmar** 2017-06-22 13:43 UTC
Labels: module:model, type:bug
