### ISSUE TITLE
Allow/Disallow elements after/before others

### ISSUE THREAD

**Issue by chihab** [ckeditor/ckeditor5-engine#1202] opened 2017-12-11 17:00 UTC
Would it be possible to control wether an element could be place before or after another one using schema definition ? 

That would be defined as before/after/inside in schema query.

```js
schema.allow( { name: 'header', before: 'div p' } );
```

**Comment by Reinmar** [comment] 2017-12-11 17:32
We're right now in a major schema refactor (see https://github.com/ckeditor/ckeditor5-engine/issues/532) and this feature is not planned there. I haven't described the new schema's design there yet but it won't contain sibling control. 

The reason is that such information doesn't tell you what to do. There's no automatic mechanism which could enforce that some element can only precede a specific set of elements. Imagine that you have such a selection:

```html
<header>foo^bar</header>
```

And someone pastes the following content:

```html
<h1>a</h1>
<h2>b</h2>
<h3>c</h3>
```

It depends on the schema configuration but in some cases this might be the natural result after pasting:

```html
<header>fooa</header>
<h2>b</h2>
<h3>c[]bar</h3>
```

But your schema requires that there's either `<p>` or `<div>` after a `<header>` so the `insertContent()` method needs to somehow produce such a result. But how? Let's say that it can guess that the following `<h2>` element should be renamed to be `<p>`. But it could also wrap it with `<div>`. This gets tricky. And we're describing here a simple scenario where we have just one simple rule. Even if we'd manage to implement some sophisticated algorithms which would handle those cases in methods like `insertContent()` or `deleteContent()`, as a feature developer you don't want to handle them in your code, so 99% of plugins would be incorrect.

Besides that, very often, the editor doesn't even know the entire context when it needs to decide how to handle a particular element (e.g. upon V->M conversion).

In other words, it's pretty much unrealistic to enforce such rules by a declarative mechanism of a schema. So, even though the new schema will fire events (to allow plugging in callbacks), we won't allow checking the surrounding of context nodes.

So what you can do?

1. Implement specific `document#change` callbacks post-fixing all incorrect operations. In other words – implement the fixing logic yourself. This is simpler for you because you know the entire schema when working on a particular editor integration. It's still not trivial, but at least doable. (I can't give you a specific example how you can do that because we're right now changing this API.)
2. Consider implementing the editor differently. Your header seems to be a separate piece of content which I guess should always be present. So move it to a separate editor or at least to a separate editable. Make the content more structured. You can read a bit lengthy but very interesting https://github.com/ckeditor/ckeditor5/issues/592 where we discuss how to handle similar situations.

**Comment by Reinmar** [comment] 2017-12-13 13:09
PS. We use a similar mechanism in [Letters](https://ckeditor.com/letters/) to the one I described in:

> Implement specific document#change callbacks post-fixing all incorrect operations.

Basically, there's that post title and it needs to always start the document. Using post-fixing is the only reliable way to do that when you need to consider the complexity caused by real-time collaboration scenarios and all the editing features. Handling this automagically through a generic algorithm that would base its actions on schema would not be feasible.

I'll close this ticket as invalid but feel free to comment further if something's unclear or if you have other ideas.

**Closed by Reinmar** 2017-12-13 13:09 UTC

**Comment by chihab** [comment] 2017-12-13 13:21
Thanks @Reinmar for your guidance. I need a bit of time to digest your answer. :)
