### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by elvispdosreis** [ckeditor/ckeditor5-engine#1622] opened 2018-12-29 16:16 UTC
is there any plugin to display the same source code in version 4

**Comment by ma2ciek** [comment] 2018-12-30 16:14
Hi, @elvispdosreis!

It's a duplicate of the https://github.com/ckeditor/ckeditor5/issues/592. There's no such plugin yet.

**Closed by ma2ciek** 2018-12-30 16:14 UTC
